project:
  type: website
  output-dir: site
  render:
    - docs/**/*.md

website:
  title: mzoo
  site-url: https://pmonad.github.io/mzoo/
  navbar:
    background: light
    right:
      - icon: github
        href: https://github.com/pmonad/mzoo
  sidebar:
    contents:
      - section: Evolution
        contents: docs/evolution/**

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    number-sections: false
    html-math-method: katex

bibliography: docs/references.bib
link-citations: true

exclude:
  - README.md
