# invoke from repo root: just docs/ <recipe>

[no-cd]
build:
    uv run --with mkdocs --with pymdown-extensions --with mkdocs-bibtex --with pypandoc-binary mkdocs build --strict --site-dir site

[no-cd]
serve *args:
    uv run --with mkdocs --with pymdown-extensions --with mkdocs-bibtex --with pypandoc-binary mkdocs serve {{args}}

[no-cd]
publish:
    uv run --with mkdocs --with pymdown-extensions --with mkdocs-bibtex --with pypandoc-binary mkdocs gh-deploy --force
